# Site settings
title: Coding - One day at a time
header-img: img/home-bg.png
email: charlotte@charlottecorini.com
copyright_name: CCorini
description: > # this means to ignore newlines until "baseurl:"
  WOW
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: charlottecorini
github_username:  CCorini
learn_profile: CCorini
email_username: charlotte@charlottecorini.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
